<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset [
<!ELEMENT dataset (attr)*>
<!ELEMENT attr (#PCDATA | item)*>
<!ELEMENT item (#PCDATA | attr)*>
<!ATTLIST attr tag CDATA #REQUIRED>
]>
<dataset>
    <!-- Specific Character Set -->
    <attr tag="00080005">ISO_IR 192</attr>
    <!-- Scheduled Procedure Step Sequence -->
    <attr tag="00400100">
        <item>
            <!-- Scheduled Station AE Title -->
            <attr tag="00400001">DCMPACS</attr>
            <!-- Scheduled Procedure Step Start Date -->
            <attr tag="00400002">20221017</attr>
            <!-- Scheduled Procedure Step Start Time -->
            <attr tag="00400003">100342</attr>
            <!-- Modality -->
            <attr tag="00080060">CR</attr>
            <!-- Scheduled Performing Physician's Name -->
            <attr tag="00400006"/>
            <!-- Scheduled Procedure Step Description -->
            <attr tag="00400007">CHEST PA</attr>
            <!-- Scheduled Procedure Step Location -->
            <attr tag="00400011">Scheduled Procedure Step Location</attr>
            <!-- Scheduled Protocol Code Sequence -->
            <attr tag="00400008">
                <item>
                    <!-- Code Value -->
                    <attr tag="00080100">PROT-2018</attr>
                    <!-- Coding Scheme Designator -->
                    <attr tag="00080102">DCM</attr>
                    <!-- Code Meaning -->
                    <attr tag="00080104">NA</attr>
                </item>
            </attr>
            <!-- Pre-Medication -->
            <attr tag="00400012">Pre-Medication</attr>
            <!-- Scheduled Procedure Step ID -->
            <attr tag="00400009">SPS-xx4</attr>
            <!-- Requested Contrast Agent -->
            <attr tag="00321070">Tidak perlu contrast</attr>
            <!-- Scheduled Procedure Step Status -->
            <attr tag="00400020">SCHEDULED</attr>
        </item>
    </attr>
    <!-- Requested Procedure ID -->
    <attr tag="00401001">RP-004</attr>
    <!-- Requested Procedure Description -->
    <attr tag="00321060">CHEST PA</attr>
    <!-- Requested Procedure Code Sequence -->
    <attr tag="00321064">
        <item>
            <!-- Code Value -->
            <attr tag="00080100">PROC-1205</attr>
            <!-- Coding Scheme Designator -->
            <attr tag="00080102">DCM</attr>
            <!-- Code Meaning -->
            <attr tag="00080104">CHEST PA</attr>
        </item>
    </attr>
    <!-- Study Instance UID -->
    <attr tag="0020000D">1.2.40.0.13.1.75172653.8.20221017.146243481</attr>
    <!-- Requested Procedure Priority -->
    <attr tag="00401003">4Low</attr>
    <!-- Accession Number -->
    <attr tag="00080050">75172653</attr>
    <!-- Requesting Physician -->
    <attr tag="00321032"/>
    <!-- Requesting Service -->
    <attr tag="00321033">INSTALASI GAWAT DARURAT</attr>
    <!-- Referring Physician's Name -->
    <attr tag="00080090">JHON HARUN NAPITUPULU,DR.SPB</attr>
    <!-- Admission ID -->
    <attr tag="00380010">ADM-1234</attr>
    <!-- Current Patient Location -->
    <attr tag="00380300">INSTALASI GAWAT DARURAT</attr>
    <!-- Patient's Name -->
    <attr tag="00100010">Pasien</attr>
    <!-- Patient ID -->
    <attr tag="00100020">1088872939</attr>
    <!-- Patients Birth Date -->
    <attr tag="00100030">20000102</attr>
    <!-- Patient's Sex -->
    <attr tag="00100040">M</attr>
    <!-- Patient's Weight -->
    <attr tag="00101030"/>
    <!-- Confidentiality constraint on patient data -->
    <attr tag="00403001">V</attr>
    <!-- Patient State -->
    <attr tag="00380500">Rawat Inap</attr>
    <!-- Pregnancy Status -->
    <attr tag="001021C0">0000</attr>
    <!-- Medical Alerts -->
    <attr tag="00102000">-</attr>
    <!-- Contrast Allergies -->
    <attr tag="00102110">Tidak Alergi Contrast</attr>
    <!-- Special Needs -->
    <attr tag="00380050"/>
</dataset>
